import * as XLSX from 'xlsx';
await import('./main.js');

const DB='financial-analysis-mobile', STORE='app', FLOW_KEY='financial-import-flow-v1', RETURN_KEY='return-import';
const stages=[
  {id:'trialBalance',title:'ميزان المراجعة',statement:'balance',hint:'الأساس المحاسبي وبناء المركز المالي'},
  {id:'income',title:'قائمة الدخل',statement:'income',hint:'الإيرادات والمصروفات وصافي الربح'},
  {id:'cashflow',title:'التدفقات النقدية',statement:'cashflow',hint:'التشغيل والاستثمار والتمويل'}
];
const aliases={
  period:['السنة','الفترة','year','period'],code:['رقم الحساب','كود الحساب','account code','code'],
  item:['اسم الحساب','الحساب','البند','account name','account','item'],nature:['طبيعة الحساب','الطبيعة','nature'],
  cls:['التصنيف الرئيسي','التصنيف','الفئة','classification','class','category'],group:['المجموعة','group'],
  debit:['ختامي مدين','رصيد ختامي مدين','الرصيد المدين','closing debit','debit'],
  credit:['ختامي دائن','رصيد ختامي دائن','الرصيد الدائن','closing credit','credit'],
  value:['القيمة','المبلغ','الرصيد','value','amount','balance'],branch:['الفرع','branch'],
  center:['مركز التكلفة','مركز الكلفة','القسم','cost center','department'],type:['نوع التدفق النقدي','نوع التدفق','cash flow type'],
  budget:['الموازنة','المخطط','budget','plan'],currency:['العملة','currency']
};
const $=id=>document.getElementById(id), clean=v=>String(v??'').trim();
const key=v=>clean(v).toLowerCase().replace(/[\s_\-–—/\\]+/g,' ').replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').trim();
const num=v=>{if(typeof v==='number')return Number.isFinite(v)?v:0;const s=clean(v),neg=/^\(.*\)$/.test(s)||/-$/.test(s),x=Number(s.replace(/[()]/g,'').replace(/[,٬\s]/g,'').replace(/[^0-9.\-]/g,''));return Number.isFinite(x)?(neg&&x>0?-x:x):0};
const uniq=a=>[...new Set(a.filter(Boolean))], id=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
const emptyFlow=()=>Object.fromEntries(stages.map(s=>[s.id,{complete:false,fileName:'',records:0,periods:[],note:''}]));
function flow(){try{return {...emptyFlow(),...JSON.parse(localStorage.getItem(FLOW_KEY)||'{}')}}catch{return emptyFlow()}}
function saveFlow(v){localStorage.setItem(FLOW_KEY,JSON.stringify(v))}
function locked(stageId,f=flow()){const i=stages.findIndex(s=>s.id===stageId);return stages.slice(0,i).some(s=>!f[s.id].complete)}
function nextStage(f=flow()){return stages.find(s=>!f[s.id].complete)?.id||'cashflow'}

function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function readState(){try{const db=await openDb(),v=await new Promise((ok,no)=>{const r=db.transaction(STORE).objectStore(STORE).get('state');r.onsuccess=()=>ok(r.result||{});r.onerror=()=>no(r.error)});db.close();return v}catch{try{return JSON.parse(localStorage.getItem('financial-state')||'{}')}catch{return {}}}}
async function writeState(s){const v={rows:Array.isArray(s.rows)?s.rows:[],period:clean(s.period),sourceFiles:Array.isArray(s.sourceFiles)?s.sourceFiles:[],lastImportAt:new Date().toISOString()};try{const db=await openDb();await new Promise((ok,no)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,'state');tx.oncomplete=ok;tx.onerror=()=>no(tx.error)});db.close()}catch{localStorage.setItem('financial-state',JSON.stringify(v))}}
function toast(t,type='info'){const e=$('toast');if(!e)return;e.textContent=t;e.dataset.type=type;e.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.add('hidden'),3000)}

const hIndex=(headers,list)=>{const h=headers.map(key);let i=h.findIndex(x=>list.some(a=>x===key(a)));if(i>=0)return i;return h.findIndex(x=>list.some(a=>x.includes(key(a))||key(a).includes(x)))};
const value=(raw,headers,list)=>{const i=hIndex(headers,list);return i>=0?raw[headers[i]]:''};
function table(sheet,stage){const m=XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:true,blankrows:false});if(!m.length)return null;let hi=0,best=-1;m.slice(0,20).forEach((r,i)=>{const hs=r.map(key),has=a=>hs.some(x=>a.some(z=>x.includes(key(z)))),years=hs.filter(x=>/^(19|20)\d{2}$/.test(x)).length;const score=(has(aliases.item)?3:0)+(stage==='trialBalance'?((has(aliases.debit)?2:0)+(has(aliases.credit)?2:0)):(has(aliases.value)?2:0)+Math.min(years,3));if(score>best){best=score;hi=i}});const headers=m[hi].map((x,i)=>clean(x)||`عمود ${i+1}`),rows=m.slice(hi+1).filter(r=>r.some(x=>clean(x)!=='')).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])));return {headers,rows}}
async function readTables(file,stage){const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true}),rx={trialBalance:/ميزان.*مراجعه|trial.*balance/i,income:/قائمه.*دخل|income|profit.*loss/i,cashflow:/تدفق|cash.*flow/i}[stage],names=wb.SheetNames.filter(n=>rx.test(key(n)));return (names.length?names:wb.SheetNames).map(n=>table(wb.Sheets[n],stage)).filter(Boolean)}
function period(raw,h,file){const p=clean(value(raw,h,aliases.period));return p||file.match(/(?:19|20)\d{2}/)?.[0]||String(new Date().getFullYear())}
function balanceClass(cls,group,item,code){const t=key(`${cls} ${group} ${item}`);if(/حقوق.*ملك|راس.*مال|احتياط|ارباح.*مدور|equity/.test(t))return'حقوق الملكية';if(/خصوم|التزام|مورد|قرض|liabilit/.test(t))return'الخصوم';if(/اصل|اصول|نقد|بنك|عميل|مخزون|asset/.test(t))return'الأصول';return clean(code)[0]==='1'?'الأصول':clean(code)[0]==='2'?'الخصوم':clean(code)[0]==='3'?'حقوق الملكية':''}
const current=(g,i)=>!/غير.*متداول|طويل.*اجل|ثابت|non current|long term/.test(key(`${g} ${i}`))&&/متداول|نقد|بنك|ذمم|عميل|مخزون|مقدم|قصير.*اجل|current/.test(key(`${g} ${i}`));
function balanceTotals(rows){const out=[];uniq(rows.map(r=>r.period)).forEach(p=>{const pr=rows.filter(r=>r.period===p),sum=a=>a.reduce((s,r)=>s+num(r.value),0),a=pr.filter(r=>r.category==='الأصول'),l=pr.filter(r=>r.category==='الخصوم'),e=pr.filter(r=>r.category==='حقوق الملكية'),base={period:p,statement:'balance',branch:'جميع الفروع',costCenter:'الإدارة',customer:'',cashflowType:'',budget:0,currency:rows[0]?.currency||'SAR',importStage:'trialBalance',generated:true};out.push({...base,id:id('total'),category:'الأصول',item:'إجمالي الأصول المتداولة',value:sum(a.filter(r=>r.isCurrent))},{...base,id:id('total'),category:'الأصول',item:'إجمالي الأصول',value:sum(a)},{...base,id:id('total'),category:'الخصوم',item:'إجمالي الخصوم المتداولة',value:sum(l.filter(r=>r.isCurrent))},{...base,id:id('total'),category:'الخصوم',item:'إجمالي الخصوم',value:sum(l)},{...base,id:id('total'),category:'حقوق الملكية',item:'حقوق الملكية',value:sum(e)})});return out}
function parseTrial(tables,file){const rows=[],checks=new Map();tables.forEach(({headers,rows:raws})=>raws.forEach(raw=>{const item=clean(value(raw,headers,aliases.item));if(!item)return;const code=clean(value(raw,headers,aliases.code)),cls=clean(value(raw,headers,aliases.cls)),group=clean(value(raw,headers,aliases.group)),cat=balanceClass(cls,group,item,code);if(!cat)return;const p=period(raw,headers,file),d=Math.abs(num(value(raw,headers,aliases.debit))),c=Math.abs(num(value(raw,headers,aliases.credit))),has=clean(value(raw,headers,aliases.debit))!==''||clean(value(raw,headers,aliases.credit))!=='';if(has){const x=checks.get(p)||{d:0,c:0};x.d+=d;x.c+=c;checks.set(p,x)}const rawNet=has?d-c:num(value(raw,headers,aliases.value)),v=cat==='الأصول'?rawNet:-rawNet;if(!v)return;rows.push({id:id('tb'),period:p,statement:'balance',category:cat,item,value:v,branch:clean(value(raw,headers,aliases.branch)),costCenter:clean(value(raw,headers,aliases.center)),customer:'',cashflowType:'',budget:0,currency:clean(value(raw,headers,aliases.currency))||'SAR',accountCode:code,accountGroup:group,isCurrent:current(group,item),importStage:'trialBalance'})}));if(!rows.length)throw Error('لم أتعرف على حسابات الأصول والخصوم وحقوق الملكية.');for(const[p,x]of checks){const diff=Math.abs(x.d-x.c),tol=Math.max(1,Math.max(x.d,x.c)*.0001);if(diff>tol)throw Error(`ميزان المراجعة غير متوازن للفترة ${p}. الفرق ${new Intl.NumberFormat('ar').format(diff)}.`)}return{rows:[...rows,...balanceTotals(rows)],periods:uniq(rows.map(r=>r.period)).sort(),note:checks.size?'تم التحقق من تساوي المدين والدائن.':'تم الاستيراد من عمود الرصيد.'}}

function expanded(tables,file){const out=[];tables.forEach(({headers,rows})=>{const ii=hIndex(headers,aliases.item);if(ii<0)return;const itemH=headers[ii],pi=hIndex(headers,aliases.period),vi=hIndex(headers,aliases.value),years=headers.filter(h=>/^(19|20)\d{2}$/.test(key(h)));let active='';rows.forEach(raw=>{const item=clean(raw[itemH]),txt=key(item);if(!item)return;if(/تشغيل|operat/.test(txt)&&/تدفق|نشاط|activit/.test(txt)){active='تشغيلي';return}if(/استثمار|invest/.test(txt)&&/تدفق|نشاط|activit/.test(txt)){active='استثماري';return}if(/تمويل|financ/.test(txt)&&/تدفق|نشاط|activit/.test(txt)){active='تمويلي';return}const base={item,category:clean(value(raw,headers,aliases.cls)),branch:clean(value(raw,headers,aliases.branch)),costCenter:clean(value(raw,headers,aliases.center)),customer:'',cashflowType:clean(value(raw,headers,aliases.type))||active,budget:num(value(raw,headers,aliases.budget)),currency:clean(value(raw,headers,aliases.currency))||'SAR'};if(years.length)years.forEach(y=>{if(clean(raw[y])!=='')out.push({...base,period:key(y),value:num(raw[y])})});else if(pi>=0&&vi>=0)out.push({...base,period:clean(raw[headers[pi]])||period(raw,headers,file),value:num(raw[headers[vi]])})})});return out}
function incomeCat(item,cat){const t=key(`${cat} ${item}`);if(/مجمل.*ربح|ربح.*تشغيلي|ربح.*قبل|صافي.*ربح|gross profit|operating profit|net profit/.test(t))return'';if(/ايراد|مبيعات|دخل|revenue|sales/.test(t)&&!/تكلف|مصروف|cost|expense/.test(t))return'الإيرادات';if(/تكلف|مصروف|رواتب|اجور|ايجار|ضريب|استهلاك|اطفاء|فوائد|عمولات|cost|expense|tax|salary|rent|interest/.test(t))return'المصروفات';return''}
function parseIncome(tables,file){let c=expanded(tables,file).map(r=>({...r,category:incomeCat(r.item,r.category)})).filter(r=>r.period&&r.category);if(!c.length)throw Error('لم أتعرف على الإيرادات والمصروفات في قائمة الدخل.');const out=[];uniq(c.map(r=>r.period)).forEach(p=>['الإيرادات','المصروفات'].forEach(cat=>{const g=c.filter(r=>r.period===p&&r.category===cat),d=g.filter(r=>!/^(اجمالي|المجموع|total)/.test(key(r.item)));out.push(...(d.length?d:g))}));const rows=out.map(r=>({...r,id:id('income'),statement:'income',value:Math.abs(num(r.value)),importStage:'income'}));if(!rows.some(r=>r.category==='الإيرادات')||!rows.some(r=>r.category==='المصروفات'))throw Error('يجب أن تحتوي قائمة الدخل على إيرادات ومصروفات.');return{rows,periods:uniq(rows.map(r=>r.period)).sort(),note:`تم اعتماد ${rows.length} بندًا من قائمة الدخل.`}}
function cashType(v,item){const t=key(`${v} ${item}`);return/تشغيل|operat/.test(t)?'تشغيلي':/استثمار|invest/.test(t)?'استثماري':/تمويل|financ/.test(t)?'تمويلي':''}
function parseCash(tables,file){const rows=expanded(tables,file).map(r=>({...r,cashflowType:cashType(r.cashflowType,r.item)})).filter(r=>r.period&&r.cashflowType&&!/صافي.*نقد|صافي.*تغير|النقديه.*بدايه|النقديه.*نهايه|فرق.*مطابق|net cash|net change/.test(key(r.item))).map(r=>({...r,id:id('cash'),statement:'cashflow',category:r.cashflowType,importStage:'cashflow'}));if(!rows.some(r=>r.cashflowType==='تشغيلي'))throw Error('يجب أن تتضمن التدفقات نشاطًا تشغيليًا.');return{rows,periods:uniq(rows.map(r=>r.period)).sort(),note:`تم اعتماد الأنشطة: ${uniq(rows.map(r=>r.cashflowType)).join('، ')}.`}}
async function parse(stage,file){const t=await readTables(file,stage);if(!t.length)throw Error('الملف لا يحتوي على جدول قابل للقراءة.');return stage==='trialBalance'?parseTrial(t,file.name):stage==='income'?parseIncome(t,file.name):parseCash(t,file.name)}

function escape(v){return clean(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function render(){const f=flow(),host=document.querySelector('#view-import .upload-panel');if(!host)return;host.innerHTML=`<div class="flow-head"><div><span class="eyebrow">تسلسل محاسبي إلزامي</span><h3>ارفع كل قائمة في مرحلتها</h3><p>يتم فحص الملف قبل فتح المرحلة التالية.</p></div><b>${stages.filter(s=>f[s.id].complete).length}/3</b></div><div class="flow-grid">${stages.map((s,i)=>{const x=f[s.id],lock=locked(s.id,f),cl=x.complete?'done':lock?'lock':'now';return`<article class="flow-card ${cl}"><div class="flow-top"><i>${x.complete?'✓':i+1}</i><span>${x.complete?'مكتمل':lock?'مقفل':'المرحلة الحالية'}</span></div><h4>${s.title}</h4><p>${s.hint}</p><small>${x.fileName?`الملف: ${escape(x.fileName)}`:'لم يتم رفع ملف'}</small><em>${x.complete?`${x.records} سجل · ${x.periods.join('، ')}`:lock?'أكمل المرحلة السابقة':'جاهز للرفع'}</em>${x.note?`<q>${escape(x.note)}</q>`:''}<div><input id="flow-${s.id}" type="file" accept=".xlsx,.xls,.csv" hidden ${lock?'disabled':''}><button class="btn primary flow-upload" data-id="${s.id}" ${lock?'disabled':''}>${x.complete?'استبدال':'رفع الملف'}</button><button class="btn ghost flow-template" data-id="${s.id}">القالب</button></div></article>`}).join('')}</div><div id="flow-message" class="flow-message">${f.cashflow.complete?'اكتملت جميع المراحل وأصبحت التحليلات جاهزة.':'ابدأ بميزان المراجعة ولا يمكن تجاوز الترتيب.'}</div>`;document.querySelectorAll('.flow-upload').forEach(b=>b.onclick=()=>$( `flow-${b.dataset.id}`)?.click());stages.forEach(s=>$( `flow-${s.id}`)?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(file)await upload(s.id,file);e.target.value=''}));document.querySelectorAll('.flow-template').forEach(b=>b.onclick=()=>template(b.dataset.id));const chips=document.querySelector('#view-import .field-chips');if(chips)chips.innerHTML='<span>ميزان المراجعة: الحساب + مدين/دائن</span><span>قائمة الدخل: البند + الفترة + القيمة</span><span>التدفقات: البند + نوع النشاط + القيمة</span>'}
async function upload(stageId,file){const f=flow();if(locked(stageId,f))return toast('أكمل المرحلة السابقة أولًا.','error');const i=stages.findIndex(s=>s.id===stageId);if(stages.slice(i+1).some(s=>f[s.id].complete)&&!confirm('استبدال هذه المرحلة سيحذف المراحل اللاحقة. هل تريد المتابعة؟'))return;const msg=$('flow-message');if(msg)msg.textContent=`جاري فحص ${file.name}…`;try{const r=await parse(stageId,file),s=await readState(),replace=stages.slice(i),rows=(s.rows||[]).filter(x=>!replace.some(z=>x.importStage===z.id||x.statement===z.statement)).concat(r.rows),periods=uniq(rows.map(x=>clean(x.period))).sort((a,b)=>a.localeCompare(b,'ar',{numeric:true}));await writeState({...s,rows,period:periods.at(-1)||'',sourceFiles:[...(s.sourceFiles||[]).filter(n=>!replace.some(z=>clean(n).startsWith(`${z.title}:`))),`${stages[i].title}: ${file.name}`]});f[stageId]={complete:true,fileName:file.name,records:r.rows.length,periods:r.periods,note:r.note,importedAt:new Date().toISOString()};stages.slice(i+1).forEach(z=>f[z.id]=emptyFlow()[z.id]);saveFlow(f);sessionStorage.setItem(RETURN_KEY,'1');toast(`تم اعتماد ${stages[i].title}.`,'success');setTimeout(()=>location.reload(),600)}catch(e){console.error(e);if(msg)msg.textContent=e.message;toast(e.message||'تعذر قراءة الملف.','error')}}
function download(name,text){const u=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function template(stage){const t={trialBalance:'\ufeffالسنة,رقم الحساب,اسم الحساب,طبيعة الحساب,التصنيف,المجموعة,ختامي مدين,ختامي دائن,الفرع,مركز التكلفة,العملة\n2026,1101,النقدية,مدين,الأصول,أصول متداولة,100000,0,الرئيسي,الخزينة,SAR\n2026,2101,ذمم الموردين,دائن,الخصوم,خصوم متداولة,0,40000,الرئيسي,المشتريات,SAR\n2026,3101,رأس المال,دائن,حقوق الملكية,حقوق الملكية,0,60000,الرئيسي,الإدارة,SAR',income:'\ufeffالبند,الفئة,2024,2025,2026,الفرع,مركز التكلفة,العملة\nمبيعات المنتجات,الإيرادات,800000,950000,1100000,الرئيسي,المبيعات,SAR\nتكلفة البضائع المباعة,المصروفات,420000,500000,580000,الرئيسي,المبيعات,SAR\nرواتب وأجور,المصروفات,180000,205000,230000,الرئيسي,الموارد البشرية,SAR',cashflow:'\ufeffالبند,نوع التدفق النقدي,2024,2025,2026,الفرع,مركز التكلفة,العملة\nتحصيلات من العملاء,تشغيلي,900000,1050000,1250000,جميع الفروع,التشغيل,SAR\nمدفوعات للموردين والموظفين,تشغيلي,-650000,-760000,-890000,جميع الفروع,التشغيل,SAR\nشراء ممتلكات ومعدات,استثماري,-90000,-110000,-135000,جميع الفروع,الاستثمار,SAR\nسداد قروض,تمويلي,-40000,-55000,-65000,جميع الفروع,التمويل,SAR'};download(`${stage}-template.csv`,t[stage])}
function replace(id,fn,text){const old=$(id);if(!old)return;const b=old.cloneNode(true);if(text)b.textContent=text;old.replaceWith(b);b.onclick=fn}
function goImport(){document.querySelector('.nav-item[data-view="import"]')?.click();setTimeout(()=>document.querySelector(`.flow-card.${flow().cashflow.complete?'done':'now'}`)?.scrollIntoView({behavior:'smooth',block:'center'}),100)}
async function clearAll(){if(!confirm('سيتم حذف جميع القوائم والنتائج. هل تريد المتابعة؟'))return;await writeState({rows:[],period:'',sourceFiles:[]});localStorage.removeItem(FLOW_KEY);sessionStorage.setItem(RETURN_KEY,'1');location.reload()}
function css(){const s=document.createElement('style');s.textContent=`.flow-head{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:20px}.flow-head h3{margin:5px 0}.flow-head p{margin:0;color:#64748b}.flow-head>b{font-size:1.4rem;color:#0f766e;background:#edf8f6;padding:12px 18px;border-radius:14px}.flow-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.flow-card{border:1px solid #dce5ea;border-radius:18px;padding:18px;background:#fff;position:relative;overflow:hidden}.flow-card:before{content:'';position:absolute;top:0;right:0;left:0;height:4px;background:#cbd5e1}.flow-card.now:before{background:#0f766e}.flow-card.done:before{background:#168a5b}.flow-card.lock{opacity:.6;background:#f8fafc}.flow-top{display:flex;justify-content:space-between;align-items:center}.flow-top i{font-style:normal;width:35px;height:35px;border-radius:50%;display:grid;place-items:center;background:#e8eef3;font-weight:800}.now .flow-top i{background:#0f766e;color:#fff}.done .flow-top i{background:#168a5b;color:#fff}.flow-top span{font-size:.78rem;font-weight:700;color:#64748b}.flow-card h4{margin:15px 0 5px}.flow-card>p{min-height:42px;color:#64748b}.flow-card small,.flow-card em,.flow-card q{display:block;margin-top:8px;padding:8px 10px;border-radius:9px;font-size:.82rem;text-decoration:none;font-style:normal}.flow-card small{background:#f1f5f9}.flow-card em{background:#eff6ff;color:#1d4ed8}.flow-card q{background:#ecfdf5;color:#047857}.flow-card>div:last-child{display:flex;gap:8px;margin-top:14px}.flow-card>div:last-child .btn{flex:1}.flow-message{margin-top:18px;padding:13px;border:1px dashed #cbd5e1;border-radius:13px;text-align:center;color:#475569}.toast[data-type=error]{background:#991b1b}.toast[data-type=success]{background:#166534}@media(max-width:900px){.flow-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
function init(){css();render();replace('quickImportBtn',goImport,'استيراد القوائم');replace('loadSampleBtn',goImport,'تجربة الاستيراد');replace('clearDataBtn',clearAll);replace('downloadTemplateBtn',()=>template(nextStage()),'قالب المرحلة');if(sessionStorage.getItem(RETURN_KEY)){sessionStorage.removeItem(RETURN_KEY);goImport()}}
init();
